#!/usr/bin/env bash
# Measure what the fofoca FFI costs mallorca: binary size, CPU, RAM.
# Regenerates every number in docs/ffi-cost.md. See that doc for the findings.
#
#   ./scripts/measure-ffi-cost.sh size      # binary size + per-crate attribution
#   ./scripts/measure-ffi-cost.sh runtime   # CPU/RAM scenario matrix (needs a display)
#   ./scripts/measure-ffi-cost.sh all
#
# Env knobs: DURATION (default 60s per run), REPEATS (default 5), OUT (bin/measure).
#
# The size baseline is a scratch-tree build: src/ is copied out and mesh.odin is
# replaced by a pure-Odin stub with the identical surface but no `foreign import`,
# so p2p.odin and main.odin compile unchanged and the only difference between the
# two binaries is the Rust archive. The repo is never modified.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="${OUT:-$ROOT/bin/measure}"
WORK="$OUT/work"
DURATION="${DURATION:-60}"
REPEATS="${REPEATS:-5}"
DEFINES=(-define:KARL2D_AUDIO_BACKEND=nil)
GRID="${GRID:-examples/_midi.orca}"

mkdir -p "$OUT" "$WORK"

log() { printf '\033[1;36m==>\033[0m %s\n' "$*" >&2; }
bytes() { stat -f%z "$1"; }

#-----------------------------------------------------------------------------#
# environment provenance — so a stale table is identifiable later
#-----------------------------------------------------------------------------#
record_env() {
	{
		echo "date	$(date -u +%Y-%m-%dT%H:%M:%SZ)"
		echo "model	$(sysctl -n hw.model)"
		echo "cpus	$(sysctl -n hw.ncpu)"
		echo "memory_bytes	$(sysctl -n hw.memsize)"
		echo "macos	$(sw_vers -productVersion)"
		echo "odin	$(odin version 2>&1 | head -1)"
		echo "rustc	$(rustc --version 2>&1 | head -1)"
		echo "git_rev	$(git rev-parse --short HEAD)"
		echo "git_dirty	$(git status --porcelain | wc -l | tr -d ' ')"
		echo "refresh_hz	$(system_profiler SPDisplaysDataType 2>/dev/null |
			awk -F': ' '/UI Looks|Refresh Rate/{print $2; exit}' || echo unknown)"
	} >"$OUT/env.tsv"
	log "environment recorded -> $OUT/env.tsv"
}

#-----------------------------------------------------------------------------#
# no-mesh baseline tree
#-----------------------------------------------------------------------------#
# Mirrors src/fofoca.odin's entire surface — same types, same proc names, same
# signatures, same helpers — as ordinary Odin returning nil/0/"". If mesh.odin
# gains or changes a symbol, this build fails to compile rather than silently
# measuring the wrong thing.
write_nomesh_stub() {
	cat >"$1" <<'ODIN'
// GENERATED by scripts/measure-ffi-cost.sh — not part of the app.
// Stands in for src/fofoca.odin with no `foreign import`, so the baseline binary
// links none of libfofoca_ffi.a while p2p.odin/main.odin compile
// verbatim. Kept signature-for-signature in step with src/fofoca.odin: a drift
// shows up as a compile error here, not as a silently wrong measurement.
#+build darwin
package main

import "core:c"
import "core:mem"
import "core:strings"

Fofoca_Pipe :: struct {}

Fofoca_Opts :: struct {
	mesh:      cstring,
	topic:     cstring,
	nick:      cstring,
	name:      cstring,
	is_public: c.int,
	mdns:      c.int,
	dht:       c.int,
	relay:     c.int,
	max_peers: c.size_t,
}

Fofoca_Frame :: struct {
	nick:     [64]u8,
	directed: c.int,
	eof:      c.int,
	len:      c.size_t,
}

fofoca_open :: proc "c" (opts: ^Fofoca_Opts) -> ^Fofoca_Pipe {return nil}
fofoca_id :: proc "c" (h: ^Fofoca_Pipe) -> cstring {return nil}
fofoca_name :: proc "c" (h: ^Fofoca_Pipe) -> cstring {return nil}
fofoca_nickname :: proc "c" (h: ^Fofoca_Pipe) -> cstring {return nil}
fofoca_recv :: proc "c" (
	h: ^Fofoca_Pipe,
	buf: [^]u8,
	cap: c.size_t,
	timeout_ms: c.int,
	frame: ^Fofoca_Frame,
) -> c.long {return 0}
fofoca_send :: proc "c" (h: ^Fofoca_Pipe, to: cstring, buf: [^]u8, len: c.size_t) -> c.long {return 0}
fofoca_send_eof :: proc "c" (h: ^Fofoca_Pipe, to: cstring) -> c.long {return 0}
fofoca_peers_json :: proc "c" (h: ^Fofoca_Pipe, buf: [^]u8, cap: c.size_t) -> c.long {return 0}
fofoca_state_json :: proc "c" (h: ^Fofoca_Pipe, buf: [^]u8, cap: c.size_t) -> c.long {return 0}
fofoca_state_merge :: proc "c" (h: ^Fofoca_Pipe, merge_json: cstring) -> c.long {return 0}
fofoca_peer_count :: proc "c" (h: ^Fofoca_Pipe) -> c.long {return 0}
fofoca_max_chunk :: proc "c" (h: ^Fofoca_Pipe) -> c.size_t {return 0}
fofoca_close :: proc "c" (h: ^Fofoca_Pipe) {}
fofoca_last_error :: proc "c" () -> cstring {return "fofoca disabled in this build"}
fofoca_version :: proc "c" () -> cstring {return "stub"}

FOFOCA_DEFAULT_MAX_PEERS :: 64

@(private = "file")
fofoca_sized_json :: proc(
	h: ^Fofoca_Pipe,
	fn: proc "c" (h: ^Fofoca_Pipe, buf: [^]u8, cap: c.size_t) -> c.long,
	allocator: mem.Allocator,
) -> string {
	cap_hint := 0
	for _ in 0 ..< 4 {
		needed := fn(h, nil, 0)
		if needed <= 0 {
			return ""
		}
		ncap := max(int(needed) + 1 + 64, cap_hint)
		buf := make([]u8, ncap, allocator)
		n := fn(h, raw_data(buf), c.size_t(len(buf)))
		if n <= 0 {
			return ""
		}
		if int(n) < len(buf) {
			return string(buf[:n])
		}
		cap_hint = int(n) + 1 + 64
	}
	return ""
}

fofoca_peers_json_string :: proc(h: ^Fofoca_Pipe, allocator: mem.Allocator) -> string {
	return fofoca_sized_json(h, fofoca_peers_json, allocator)
}

fofoca_state_json_string :: proc(h: ^Fofoca_Pipe, allocator: mem.Allocator) -> string {
	return fofoca_sized_json(h, fofoca_state_json, allocator)
}

fofoca_clone_cstring :: proc(s: cstring, allocator := context.allocator) -> string {
	if s == nil {
		return ""
	}
	out, _ := strings.clone_from_cstring(s, allocator)
	return out
}

fofoca_last_error_string :: proc(allocator := context.temp_allocator) -> string {
	return fofoca_clone_cstring(fofoca_last_error(), allocator)
}
ODIN
}

prepare_nomesh_tree() {
	local tree="$WORK/src-nomesh"
	rm -rf "$tree"
	mkdir -p "$tree"
	# -a keeps the tree an exact copy; only mesh.odin is then swapped.
	rsync -a --delete "$ROOT/src/" "$tree/"
	write_nomesh_stub "$tree/fofoca.odin"
	# main.odin reaches out of the package with `import k2 "../karl2d"` and
	# `#load("../assets/...")`, so the copy's parent has to look like the repo
	# root. Symlinks, not copies — karl2d alone is large.
	for d in karl2d assets fofoca; do
		ln -sfn "$ROOT/$d" "$WORK/$d"
	done
	echo "$tree"
}

#-----------------------------------------------------------------------------#
# size
#-----------------------------------------------------------------------------#
build_variants() {
	local tree
	tree="$(prepare_nomesh_tree)"

	log "building mesh binary (-o:speed)"
	just fofoca >/dev/null
	odin build src -o:speed "${DEFINES[@]}" -out:"$OUT/mallorca-mesh" 2>&1 | grep -v 'duplicate librar' || true

	log "building no-mesh baseline (-o:speed)"
	odin build "$tree" -o:speed "${DEFINES[@]}" -out:"$OUT/mallorca-nomesh" 2>&1 | grep -v 'duplicate librar' || true

	log "building -o:size variants (reduction lever)"
	odin build src -o:size "${DEFINES[@]}" -out:"$OUT/mallorca-mesh-osize" 2>&1 | grep -v 'duplicate librar' || true
	odin build "$tree" -o:size "${DEFINES[@]}" -out:"$OUT/mallorca-nomesh-osize" 2>&1 | grep -v 'duplicate librar' || true

	log "building profile binary (-define:MALLORCA_PROFILE=true)"
	odin build src -o:speed "${DEFINES[@]}" -define:MALLORCA_PROFILE=true \
		-out:"$OUT/mallorca-prof" 2>&1 | grep -v 'duplicate librar' || true
	odin build "$tree" -o:speed "${DEFINES[@]}" -define:MALLORCA_PROFILE=true \
		-out:"$OUT/mallorca-nomesh-prof" 2>&1 | grep -v 'duplicate librar' || true

	for v in mallorca-mesh mallorca-nomesh mallorca-mesh-osize mallorca-nomesh-osize; do
		cp "$OUT/$v" "$OUT/$v.stripped"
		strip -x "$OUT/$v.stripped"
	done
}

measure_size() {
	build_variants

	log "collecting sizes"
	{
		echo "variant	bytes"
		for v in mallorca-mesh mallorca-nomesh mallorca-mesh-osize mallorca-nomesh-osize; do
			echo "$v	$(bytes "$OUT/$v")"
			echo "$v.stripped	$(bytes "$OUT/$v.stripped")"
		done
		local ar="fofoca/lib/libfofoca_ffi.a"
		[ -f "$ar" ] && echo "staticlib.a	$(bytes "$ar")"
	} >"$OUT/size.tsv"

	log "collecting per-section breakdown"
	size -m "$OUT/mallorca-mesh" >"$OUT/sections-mesh.txt"
	size -m "$OUT/mallorca-nomesh" >"$OUT/sections-nomesh.txt"
	# Join the two `size -m` outputs on section name and diff them.
	{
		echo "segment	section	fofoca_bytes	nomesh_bytes	delta"
		awk '
			/^Segment/ { seg = $2; sub(/:$/, "", seg); next }
			/^\tSection/ { sec = $2; sub(/:$/, "", sec); print seg "\t" sec "\t" $3 }
		' "$OUT/sections-mesh.txt" | sort >"$WORK/sec-mesh"
		awk '
			/^Segment/ { seg = $2; sub(/:$/, "", seg); next }
			/^\tSection/ { sec = $2; sub(/:$/, "", sec); print seg "\t" sec "\t" $3 }
		' "$OUT/sections-nomesh.txt" | sort >"$WORK/sec-nomesh"
		join -t'	' -j1 -a1 -a2 -e 0 -o 0,1.2,2.2 \
			<(awk -F'\t' '{print $1"/"$2"\t"$3}' "$WORK/sec-mesh") \
			<(awk -F'\t' '{print $1"/"$2"\t"$3}' "$WORK/sec-nomesh") |
			awk -F'\t' '{split($1,p,"/"); printf "%s\t%s\t%d\t%d\t%d\n", p[1], p[2], $2, $3, $2-$3}' |
			sort -t'	' -k5 -rn
	} >"$OUT/sections.tsv"

	attribute_crates
	rollup_families
	report_size
}

# Per-crate numbers are too granular to reason about; what matters is which
# *subsystem* the bytes belong to and whether mallorca uses it at all.
rollup_families() {
	python3 - "$OUT/crates.tsv" "$OUT/families.tsv" <<'PY'
import sys
src, dst = sys.argv[1], sys.argv[2]
FAMILIES = [
    ('Rust core/alloc/std', ['rust core/alloc/std', 'hashbrown']),
    ('tokio + futures', ['tokio', 'tokio_util', 'futures_util', 'futures_channel',
                         'futures_buffered', 'futures_lite', 'crossbeam_channel',
                         'futures_sink', 'futures_core', 'futures_task', 'pin_project_lite']),
    ('HTTP/relay stack', ['h2', 'hyper', 'hyper_util', 'http', 'reqwest', 'attohttpc',
                          'tokio_websockets', 'http_body', 'http_body_util', 'httparse']),
    ('TLS + crypto', ['rustls', 'curve25519_dalek', 'ring', 'ring (crypto asm)', 'der',
                      'webpki', 'tokio_rustls', 'rustls_pki_types', 'webpki_roots',
                      'x25519_dalek', 'chacha20poly1305', 'sha2', 'argon2', 'spki', 'pkcs8']),
    ('automerge (CRDT)', ['automerge', 'hexane']),
    ('iroh endpoint + transports', ['iroh', 'iroh_gossip', 'iroh_relay', 'iroh_base',
                                    'iroh_multihop_transport', 'netwatch', 'netdev',
                                    'iroh_mdns_address_lookup', 'irpc', 'socket2',
                                    'n0_watcher', 'n0_future', 'n0_error']),
    ('DNS discovery', ['hickory_proto', 'hickory_resolver', 'hickory_net', 'iroh_dns',
                       'simple_dns', 'idna', 'icu_normalizer', 'icu_properties']),
    ('QUIC (noq)', ['noq', 'noq_proto']),
    ('tracing + regex (EnvFilter)', ['tracing', 'tracing_subscriber', 'tracing_core',
                                     'regex_syntax', 'regex_automata', 'tracing_log']),
    ('mesh engine + FFI shim', ['fofoca', 'fofoca_ffi']),
    ('NAT traversal + DHT + mDNS', ['portmapper', 'igd_next', 'swarm_discovery',
                                    'n0_mainline', 'serde_bencode', 'plist', 'xml', 'quick_xml']),
    ('macOS objc2 bindings', ['objc2_foundation', 'security_framework', 'objc2',
                              'objc2_core_foundation']),
    ('serde + json', ['serde', 'serde_core', 'serde_json', 'serde_derive']),
    ('Odin: app + runtime + karl2d', ['odin runtime', 'mallorca (odin)',
                                      'karl2d (vendored gfx)', 'karl2d', 'encoding_json']),
]
rows = {}
for line in open(src):
    f = line.rstrip('\n').split('\t')
    if len(f) >= 2 and f[0] not in ('bucket', 'TOTAL'):
        rows[f[0]] = int(f[1])
seen, out = set(), []
for fam, members in FAMILIES:
    out.append((sum(rows.get(m, 0) for m in members), fam))
    seen.update(m for m in members if m in rows)
out.append((sum(v for k, v in rows.items() if k not in seen),
            'everything else (200+ small crates, unattributed)'))
grand = sum(rows.values())
with open(dst, 'w') as f:
    f.write('family\tbytes\tpct_of_text\n')
    for tot, fam in sorted(out, reverse=True):
        f.write(f'{fam}\t{tot}\t{100.0*tot/grand:.1f}\n')
    f.write(f'TOTAL\t{grand}\t100.0\n')
print('wrote', dst)
PY
}

# Per-crate attribution. bloaty is better (it uses DWARF compile units); the
# nm fallback needs no extra tooling and is accurate enough at crate
# granularity: symbol size = distance to the next symbol address.
attribute_crates() {
	if command -v bloaty >/dev/null 2>&1; then
		log "attributing with bloaty"
		bloaty -d compileunits -n 40 "$OUT/mallorca-mesh" >"$OUT/bloaty.txt" 2>/dev/null || true
	else
		log "bloaty not installed (brew install bloaty for compile-unit detail); using nm"
	fi

	log "attributing with nm address deltas"
	# -n sorts by address; -U hides undefined. Sizes come from the gap to the
	# next symbol, which is why the list must stay address-ordered.
	nm -n -U "$OUT/mallorca-mesh" 2>/dev/null |
		awk '$2 ~ /^[tT]$/ {print $1, $3}' >"$WORK/text-syms.txt"

	python3 - "$WORK/text-syms.txt" "$OUT/crates.tsv" <<'PY'
import re, subprocess, sys
from collections import defaultdict

src, dst = sys.argv[1], sys.argv[2]
rows = []
with open(src) as f:
    for line in f:
        addr, _, name = line.strip().partition(' ')
        if name:
            rows.append((int(addr, 16), name))

# __text has no per-symbol size in Mach-O, so a symbol's size is the gap to the
# next one. That is why the nm output must stay address-ordered (-n).
sizes = []
for i, (addr, name) in enumerate(rows):
    end = rows[i + 1][0] if i + 1 < len(rows) else addr
    sizes.append((max(end - addr, 0), name))

names = [n for _, n in sizes]
try:
    dem = subprocess.run(['c++filt'], input='\n'.join(names), text=True,
                         capture_output=True, check=True).stdout.splitlines()
except Exception:
    dem = names
if len(dem) != len(names):
    dem = names

# core/alloc/std own the generic machinery but rarely the reason it exists:
# `core::ptr::drop_in_place<rustls::...>` is rustls' cost, not core's. So the
# first *non-runtime* crate in the name wins, and the runtime crates are only
# used when nothing else appears.
RUNTIME = {'core', 'alloc', 'std', 'compiler_builtins', 'rustc_demangle'}
# Match a whole `crate::path::to::thing` and capture only the head, so that in
# `core::ptr::drop_in_place<rustls::msgs::...>` the candidates are [core,
# rustls] and not core's own module names.
PATHHEAD = re.compile(r'\b([a-z][a-z0-9_]{1,30})(?:::[A-Za-z_][A-Za-z0-9_]*)+')
# v0 mangling (_RNv...) survives c++filt untouched; its crate name is
# length-prefixed right after the Cs<disambiguator>_ marker.
V0 = re.compile(r'Cs[0-9A-Za-z]+_(\d+)([A-Za-z_][A-Za-z0-9_]*)')
# ring/BoringSSL assembly comes in with no namespace at all.
ASM = re.compile(r'^_+(ring_core|ecp_|p256|p384|bn_|gcm_|aes|sha256|sha512|ChaCha20|poly1305|x25519|curve25519|fiat_|LIMBS?_|OPENSSL|CRYPTO|GFp)')
MANGLED_RUST = re.compile(r'^_+(ZN|R[A-Za-z])')

def bucket(dem_name, raw):
    if raw.startswith('_karl2d') or '[karl2d' in raw or raw.startswith('_stbtt'):
        return 'karl2d (vendored gfx)'
    if re.match(r'^_(main|core)::', raw):
        return 'mallorca (odin)'
    if ASM.match(raw):
        return 'ring (crypto asm)'
    # The FFI shim's own C exports carry no namespace of any kind.
    if re.match(r'^_fofoca_[a-z_]+$', raw):
        return 'fofoca_ffi'
    # Odin mangles as `pkg::name`; Rust always arrives as _ZN…/_R…. So an
    # unmangled name containing :: is Odin's, whichever package it came from.
    if not MANGLED_RUST.match(raw) and '::' in raw:
        return 'odin runtime'
    m = V0.search(raw)
    if m:
        n, rest = int(m.group(1)), m.group(2)
        crate = rest[:n]
        if crate and crate not in RUNTIME:
            return crate
    # Drop the trailing `::h<16 hex>` disambiguator: without this, the tail of
    # `<&T as core::fmt::Debug>::fmt::h00b6…` reads as a path headed by `fmt`.
    clean = re.sub(r'::h[0-9a-f]{16}\b', '', dem_name.replace('$LT$', '<').replace('..', '::'))
    hits = PATHHEAD.findall(clean)
    for h in hits:
        if h not in RUNTIME:
            return h
    if hits:
        return 'rust core/alloc/std'
    if ASM.match(raw):
        return 'ring (crypto asm)'
    return 'other/unattributed'

totals, counts = defaultdict(int), defaultdict(int)
for (sz, raw), d in zip(sizes, dem):
    b = bucket(d, raw)
    if len(b) > 32:
        b = 'other/unattributed'
    totals[b] += sz
    counts[b] += 1

grand = sum(totals.values())
with open(dst, 'w') as f:
    f.write('bucket\tbytes\tsymbols\tpct_of_text\n')
    for b, sz in sorted(totals.items(), key=lambda kv: -kv[1]):
        f.write(f'{b}\t{sz}\t{counts[b]}\t{100.0*sz/grand:.2f}\n')
    f.write(f'TOTAL\t{grand}\t{len(sizes)}\t100.00\n')
print(f'attributed {grand} bytes of __text across {len(totals)} buckets -> {dst}')
PY
}

report_size() {
	local mesh nomesh fofoca_s nomesh_s
	mesh=$(bytes "$OUT/mallorca-mesh")
	nomesh=$(bytes "$OUT/mallorca-nomesh")
	fofoca_s=$(bytes "$OUT/mallorca-mesh.stripped")
	nomesh_s=$(bytes "$OUT/mallorca-nomesh.stripped")
	log "size delta (unstripped): $((mesh - nomesh)) bytes"
	log "size delta (stripped):   $((fofoca_s - nomesh_s)) bytes"
	column -t -s$'\t' "$OUT/size.tsv" >&2
}

#-----------------------------------------------------------------------------#
# runtime: CPU / RAM
#-----------------------------------------------------------------------------#
# Sample a live pid at 1 Hz. `time=` is cumulative CPU, so the first-to-last
# delta is the honest CPU-seconds figure; %cpu on a vsync-locked loop just
# tracks the display refresh rate.
sample_pid() {
	local pid="$1" csv="$2" secs="$3"
	echo "t,rss_kb,vsz_kb,pcpu,cputime,threads" >"$csv"
	for ((t = 0; t < secs; t++)); do
		kill -0 "$pid" 2>/dev/null || break
		local line threads
		line=$(ps -o rss=,vsz=,%cpu=,time= -p "$pid" 2>/dev/null | tr -s ' ' | sed 's/^ //') || break
		[ -z "$line" ] && break
		# `ps -M` prints a header, then one process row, then one row per
		# thread — so subtract both leading rows.
		threads=$(($(ps -M "$pid" 2>/dev/null | wc -l | tr -d ' ') - 2))
		echo "$t,$(echo "$line" | tr ' ' ','),$threads" >>"$csv"
		# Deep memory snapshot once, ~80% through, while steady.
		if [ "$t" -eq $((secs * 4 / 5)) ]; then
			footprint -p "$pid" >"${csv%.csv}.footprint.txt" 2>/dev/null || true
			vmmap -summary "$pid" >"${csv%.csv}.vmmap.txt" 2>/dev/null || true
		fi
		sleep 1
	done
}

# Wait for a create-room process to print its bare base58 room hash.
wait_for_hash() {
	local logfile="$1" tries=0
	while [ $tries -lt 120 ]; do
		local h
		h=$(grep -m1 -E '^[1-9A-HJ-NP-Za-km-z]{40,}$' "$logfile" 2>/dev/null || true)
		if [ -n "$h" ]; then
			echo "$h"
			return 0
		fi
		sleep 0.5
		tries=$((tries + 1))
	done
	return 1
}

# run_single <scenario> <binary> <repeat> [app args...]
run_single() {
	local name="$1" bin="$2" rep="$3"
	shift 3
	local tag="$OUT/run-$name-$rep"
	"$bin" "$GRID" --profile-run="$DURATION" "$@" >"$tag.stdout" 2>"$tag.stderr" &
	local pid=$!
	sleep 2 # let the window come up before sampling
	sample_pid "$pid" "$tag.csv" "$((DURATION - 3))"
	wait "$pid" 2>/dev/null || true
}

# run_pair <scenario> <repeat> [extra joiner/host args...] — host creates the
# room, joiner joins it; both are sampled.
run_pair() {
	local name="$1" rep="$2"
	shift 2
	local htag="$OUT/run-$name-host-$rep" jtag="$OUT/run-$name-join-$rep"
	local bin="$OUT/mallorca-prof"

	# The host runs longer than the joiner and is allowed to exit on its own
	# deadline: killing it would skip prof_dump() and lose its histograms.
	"$bin" "$GRID" --create-room --room-name=measure \
		--profile-run="$((DURATION + 25))" "$@" >"$htag.stdout" 2>"$htag.stderr" &
	local hpid=$!
	local hash
	if ! hash=$(wait_for_hash "$htag.stdout"); then
		log "  !! host never printed a room hash; skipping $name rep $rep"
		kill "$hpid" 2>/dev/null || true
		return 1
	fi

	"$bin" "$GRID" --join-room="$hash" \
		--profile-run="$DURATION" "$@" >"$jtag.stdout" 2>"$jtag.stderr" &
	local jpid=$!
	sleep 3 # allow the two to actually connect before sampling
	sample_pid "$hpid" "$htag.csv" "$((DURATION - 5))" &
	local s1=$!
	sample_pid "$jpid" "$jtag.csv" "$((DURATION - 5))"
	wait $s1 2>/dev/null || true
	wait "$jpid" 2>/dev/null || true
	wait "$hpid" 2>/dev/null || true
}

measure_runtime() {
	[ -x "$OUT/mallorca-prof" ] || {
		log "profile binaries missing — run the size phase first"
		exit 1
	}
	log "runtime matrix: ${REPEATS} repeats x ${DURATION}s per scenario"
	log "keep the machine on AC, windows frontmost, and hands off the keyboard"

	for ((r = 1; r <= REPEATS; r++)); do
		log "repeat $r/$REPEATS"
		log "  A nomesh, no room"
		run_single A "$OUT/mallorca-nomesh-prof" "$r"
		log "  B mesh linked, no room"
		run_single B "$OUT/mallorca-prof" "$r"
		log "  C mesh, room open, no peer"
		run_single C "$OUT/mallorca-prof" "$r" --create-room --room-name=measure
		log "  D mesh, one peer, paused"
		run_pair D "$r" --profile-no-play || true
		log "  E mesh, one peer, playing"
		run_pair E "$r" || true
		log "  F mesh, room open, discovery off"
		run_single F "$OUT/mallorca-prof" "$r" --create-room --room-name=measure \
			--no-mdns --no-dht --no-relay
	done

	summarize_runtime
}

summarize_runtime() {
	log "summarizing"
	python3 - "$OUT" <<'PY'
import csv, glob, os, re, statistics, sys

out = sys.argv[1]

def cputime_seconds(s):
    # ps `time` is [[HH:]MM:]SS[.ss]
    parts = s.split(':')
    try:
        parts = [float(p) for p in parts]
    except ValueError:
        return None
    total = 0.0
    for p in parts:
        total = total * 60 + p
    return total

def load(path):
    with open(path) as f:
        rows = list(csv.DictReader(f))
    rows = [r for r in rows if r.get('rss_kb')]
    if len(rows) < 5:
        return None
    rss = [int(r['rss_kb']) for r in rows]
    vsz = [int(r['vsz_kb']) for r in rows]
    thr = [int(r['threads']) for r in rows]
    ct = [cputime_seconds(r['cputime']) for r in rows]
    ct = [c for c in ct if c is not None]
    if len(ct) < 2:
        return None
    span = len(rows) - 1
    return {
        'cpu_pct': 100.0 * (ct[-1] - ct[0]) / span if span else 0.0,
        'cpu_s': ct[-1] - ct[0],
        'rss_mb_med': statistics.median(rss) / 1024.0,
        'rss_mb_peak': max(rss) / 1024.0,
        'rss_mb_growth': (rss[-1] - rss[0]) / 1024.0,
        'vsz_gb': statistics.median(vsz) / 1024.0 / 1024.0,
        'threads': statistics.median(thr),
        'samples': len(rows),
    }

def prof(path):
    d = {}
    if not os.path.exists(path):
        return d
    for line in open(path):
        f = line.rstrip('\n').split('\t')
        if f[0] == 'prof' and len(f) == 8 and f[1] != 'name':
            d[f[1]] = {'count': int(f[2]), 'mean': int(f[3]), 'p50': int(f[4]),
                       'p95': int(f[5]), 'p99': int(f[6]), 'max': int(f[7])}
        elif f[0] == 'profv' and len(f) == 3:
            d[f[1]] = float(f[2])
    return d

scen = {}
for csvpath in sorted(glob.glob(os.path.join(out, 'run-*.csv'))):
    m = re.match(r'run-([A-F](?:-host|-join)?)-\d+\.csv$', os.path.basename(csvpath))
    if not m:
        continue
    st = load(csvpath)
    if not st:
        continue
    st['prof'] = prof(csvpath[:-4] + '.stdout')
    scen.setdefault(m.group(1), []).append(st)

def med(vals):
    return statistics.median(vals) if vals else 0.0

def iqr(vals):
    if len(vals) < 4:
        return 0.0
    q = statistics.quantiles(vals, n=4)
    return q[2] - q[0]

with open(os.path.join(out, 'runtime.tsv'), 'w') as f:
    f.write('scenario\truns\tcpu_pct\tcpu_pct_iqr\trss_mb\trss_peak_mb\trss_growth_mb\t'
            'threads\tframes\tframe_p50_us\tframe_p99_us\tframe_max_us\t'
            'poll_mean_us\tpoll_p50_us\tpoll_p99_us\troster_p99_us\troster_max_us\t'
            'send_p99_us\tsend_max_us\topen_ms\twindow_ms\n')
    for name in sorted(scen):
        runs = scen[name]
        g = lambda k: [r[k] for r in runs]
        def pv(metric, field):
            vals = [r['prof'][metric][field] for r in runs if metric in r['prof']]
            return med(vals)
        f.write('\t'.join(str(x) for x in [
            name, len(runs),
            f"{med(g('cpu_pct')):.1f}", f"{iqr(g('cpu_pct')):.1f}",
            f"{med(g('rss_mb_med')):.1f}", f"{med(g('rss_mb_peak')):.1f}",
            f"{med(g('rss_mb_growth')):.1f}",
            int(med(g('threads'))), int(pv('frame', 'count')),
            int(pv('frame', 'p50')), int(pv('frame', 'p99')), int(pv('frame', 'max')),
            int(pv('p2p_poll', 'mean')), int(pv('p2p_poll', 'p50')), int(pv('p2p_poll', 'p99')),
            int(pv('p2p_roster_tick', 'p99')), int(pv('p2p_roster_tick', 'max')),
            int(pv('p2p_send_own', 'p99')), int(pv('p2p_send_own', 'max')),
            int(med([r['prof'].get('p2p_open_us', 0) for r in runs]) / 1000),
            int(med([r['prof'].get('window_up_us', 0) for r in runs]) / 1000),
        ]) + '\n')
print('wrote', os.path.join(out, 'runtime.tsv'))
PY
	column -t -s$'\t' "$OUT/runtime.tsv" >&2 || true
}

#-----------------------------------------------------------------------------#
case "${1:-all}" in
size)
	record_env
	measure_size
	;;
runtime)
	record_env
	measure_runtime
	;;
all)
	record_env
	measure_size
	measure_runtime
	;;
*)
	echo "usage: $0 [size|runtime|all]" >&2
	exit 1
	;;
esac

log "artifacts in $OUT"
